services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
        restart: always
    db:
        image: mysql:8.0
        ports: 
            - "3307:3307"
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: sqlitraining
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./udf:/usr/lib/mysql/plugin
            - persistent:/var/lib/mysql
        networks:
            - default
        restart: always
    vaccine:
      build:
          context: .
          dockerfile: DockerfileVaccine
      image: vaccine
      container_name: vaccine
      networks:
          - default
        
          - ../vaccine:/usr/src/app


volumes:
    persistent: