FROM python:3.12
WORKDIR /usr/local/app


# Install the application dependencies using apt-get
RUN apt-get update && apt-get install -y \
    tor \
    nginx \
    apache2 \
    openssh-server \
    vim \
    nano

# Install the application dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Create a user and set a password
RUN useradd -m -s /bin/bash appuser && echo "appuser:password" | chpasswd

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the SSH configuration file
COPY sshd_config /etc/ssh/sshd_config

# Copy in the source code
COPY src ./src
EXPOSE 80
EXPOSE 4242

#add the tor configuration file
COPY torrc /etc/tor/torrc

# Copy the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
# CMD ["nginx", "-g", "daemon off;"]